import z from 'zod';

import { DEFAULT_DB_PATH } from '../constants.js';
import { createEchoesRAG } from '../rag/index.js';
import type { ToolConfig } from '../types.js';

export const reviewGenerateConfig: ToolConfig = {
  name: 'review-generate',
  description: 'Generate review file for pending entity/relation extractions.',
  arguments: {
    arc: 'Arc name to generate review for.',
    output: 'Output file path (default: .echoes-review.yaml).',
    filter: 'Filter by review status: pending or all (default: pending).',
    dbPath: `Database path (default: ${DEFAULT_DB_PATH}).`,
  },
};

export const reviewGenerateSchema = z.object({
  arc: z.string().min(1).describe(reviewGenerateConfig.arguments.arc),
  output: z.string().optional().describe(reviewGenerateConfig.arguments.output),
  filter: z.enum(['pending', 'all']).optional().describe(reviewGenerateConfig.arguments.filter),
  dbPath: z.string().default(DEFAULT_DB_PATH).describe(reviewGenerateConfig.arguments.dbPath),
});

export type ReviewGenerateInput = z.infer<typeof reviewGenerateSchema>;

interface ReviewEntity {
  id: string;
  name: string;
  type: string;
  description: string;
  aliases: string[];
  status: string;
}

interface ReviewRelation {
  id: string;
  source: string;
  target: string;
  type: string;
  description: string;
  weight: number;
  chapters: string[];
  status: string;
}

interface ReviewFile {
  metadata: { arc: string; generated_at: string; generated_by: string };
  entities: ReviewEntity[];
  relations: ReviewRelation[];
}

function toYaml(obj: ReviewFile): string {
  const lines: string[] = [];

  lines.push('# Generated by echoes-mcp-server');
  lines.push(`# Arc: ${obj.metadata.arc}`);
  lines.push(`# Generated at: ${obj.metadata.generated_at}`);
  lines.push('');

  lines.push('entities:');
  if (obj.entities.length === 0) {
    lines.push('  []');
  } else {
    for (const e of obj.entities) {
      lines.push(`  - id: "${e.id}"`);
      lines.push(`    name: "${e.name}"`);
      lines.push(`    type: "${e.type}"`);
      lines.push(`    description: "${e.description}"`);
      lines.push(`    aliases: [${e.aliases.map((a) => `"${a}"`).join(', ')}]`);
      lines.push(`    status: ${e.status}`);
      lines.push('');
    }
  }

  lines.push('relations:');
  if (obj.relations.length === 0) {
    lines.push('  []');
  } else {
    for (const r of obj.relations) {
      lines.push(`  - id: "${r.id}"`);
      lines.push(`    source: "${r.source}"`);
      lines.push(`    target: "${r.target}"`);
      lines.push(`    type: "${r.type}"`);
      lines.push(`    description: "${r.description}"`);
      lines.push(`    weight: ${r.weight}`);
      lines.push(`    chapters: [${r.chapters.map((c) => `"${c}"`).join(', ')}]`);
      lines.push(`    status: ${r.status}`);
      lines.push('');
    }
  }

  lines.push('# Add new entities/relations below:');
  lines.push('additions:');
  lines.push('  entities: []');
  lines.push('  relations: []');

  return lines.join('\n');
}

function isPending(fields: Record<string, unknown> | undefined): boolean {
  return !fields?.review_status || fields.review_status === 'pending';
}

export async function reviewGenerate(
  input: ReviewGenerateInput,
): Promise<{ file: string; content: string; stats: { entities: number; relations: number } }> {
  const { arc, dbPath } = reviewGenerateSchema.parse(input);
  const output = input.output || '.echoes-review.yaml';
  const filter = input.filter || 'pending';

  const { storage } = createEchoesRAG({ dbPath, arc });

  const allEntities = await storage.graph.getEntities();
  const filteredEntities = allEntities.filter((e) => filter === 'all' || isPending(e.fields));

  const allRelations: Array<{
    id: string;
    sourceId: string;
    targetId: string;
    type: string;
    description: string;
    sourceChunkIds: string[];
    fields?: Record<string, unknown>;
  }> = [];
  const seen = new Set<string>();
  for (const e of allEntities) {
    for (const r of await storage.graph.getRelations(e.id, 'out')) {
      if (seen.has(r.id)) continue;
      seen.add(r.id);
      allRelations.push(r);
    }
  }
  const filteredRelations = allRelations.filter((r) => filter === 'all' || isPending(r.fields));

  const reviewFile: ReviewFile = {
    metadata: { arc, generated_at: new Date().toISOString(), generated_by: 'echoes-mcp-server' },
    entities: filteredEntities.map((e) => ({
      id: e.id,
      name: e.name,
      type: e.type,
      description: e.description,
      aliases: (e.fields?.aliases as string[]) || [],
      status: (e.fields?.review_status as string) || 'pending',
    })),
    relations: filteredRelations.map((r) => ({
      id: r.id,
      source: r.sourceId.split(':').pop() || '',
      target: r.targetId.split(':').pop() || '',
      type: r.type,
      description: r.description,
      weight: Number(r.fields?.weight ?? 0.5),
      chapters: r.sourceChunkIds,
      status: (r.fields?.review_status as string) || 'pending',
    })),
  };

  return {
    file: output,
    content: toYaml(reviewFile),
    stats: { entities: reviewFile.entities.length, relations: reviewFile.relations.length },
  };
}
